#ifndef AUTONS_H
#define AUTONS_H

enum class AutonRoutine {
    NONE,
    TEST,
    RED_LEFT,
    RED_RIGHT,
    BLUE_LEFT,
    BLUE_RIGHT,
    AUTO_CORRECT_BLUE_RIGHT,
    AUTO_CORRECT_BLUE_LEFT,
    AUTO_CORRECT_RED_RIGHT,
    AUTO_CORRECT_RED_LEFT,
    SIMPLE_AUTON_LEFT,
    SIMPLE_AUTON_RIGHT,
    SKILLS,
    HARD_CODED_RIGHT,
    HARD_CODED_MESSUP_RIGHT,
    HARD_CODED_MESSUP_RIGHT2,
    SHIT_SKILLS,
    SKILLS2,
    AUTON_SKILLS
};

extern AutonRoutine selectedAuton;

void runAutonomous();

#endif
